### ISSUE TITLE
Can't make ServerHanler work with OpenApiHandler, is there any example or tutorial?

### ISSUE THREAD

**Issue by xiongxiong** [haskell-webgear/webgear#44]
webgear version: 1.1.0

`
-- use effects here
type App = Eff (Logging : FileSystem : Reader AppEnv : IOE : '[])

-- here the type is ok
routes :: RequestHandler (ServerHandler App) ts
routes = _

-- problem here: I cannot make routes work with toOpenApi
allRoutes :: RequestHandler (ServerHandler App) ts
allRoutes = routes
    <+> [match| /openapi |] (swaggerUI $ toOpenApi @App @(With Request '[]) @Response routes)
`

I cannot make ServerHanler work with toOpenApi, is there any example or tutorial? Thanks.

This is a wonderful library by design, I want to try it a bit.

**Comment by rkaippully** [comment]
You should use this instead of `ServerHandler`.
```hs
routes :: StdHandler h App => RequestHandler h '[]
```

At the top level of the API, you might need additional constraints. You may omit the type annotation if there are too many constraints. See [this example](https://github.com/haskell-webgear/webgear/blob/v1.1.0/webgear-example-realworld/src/Main.hs) which is following that approach.

There is a tutorial available here (eve though it does not cover openapi generation): https://haskell-webgear.github.io

**Comment by xiongxiong** [comment]
Thanks a lot. I made it. It will be better if there is a part in tutorial for openapi generation.
